"""add base models

Revision ID: 12a760e56275
Revises: 
Create Date: 2017-07-06 01:23:56.350132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a760e56275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_categories_name'), 'place_categories', ['name'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_image', sa.String(), nullable=True),
    sa.Column('image_urls', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('seasons_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('season_description', sa.String(), nullable=True),
    sa.Column('months_available', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('harvest_description', sa.String(), nullable=True),
    sa.Column('taste_description', sa.String(), nullable=True),
    sa.Column('smell_description', sa.String(), nullable=True),
    sa.Column('uses_description', sa.String(), nullable=True),
    sa.Column('prep_description', sa.String(), nullable=True),
    sa.Column('storage_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_primary_name'), 'plants', ['primary_name'], unique=True)
    op.create_table('plant_place',
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_place')
    op.drop_index(op.f('ix_plants_primary_name'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_place_categories_name'), table_name='place_categories')
    op.drop_table('place_categories')
    # ### end Alembic commands ###
