"""base places

Revision ID: c5c878c4db2f
Revises: 
Create Date: 2017-07-27 17:16:19.572142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5c878c4db2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('superplace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superplace_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('season_description', sa.String(), nullable=True),
    sa.Column('months_available', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('harvest_description', sa.String(), nullable=True),
    sa.Column('taste_description', sa.String(), nullable=True),
    sa.Column('smell_description', sa.String(), nullable=True),
    sa.Column('uses_description', sa.String(), nullable=True),
    sa.Column('prep_description', sa.String(), nullable=True),
    sa.Column('storage_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_primary_name'), 'plants', ['primary_name'], unique=True)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('_password', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_place',
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_place')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_primary_name'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
