"""add plant uses

Revision ID: f5f150d2a14f
Revises: b61a04636eaf
Create Date: 2017-08-05 19:04:06.746862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5f150d2a14f'
down_revision = 'b61a04636eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('uses', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'uses')
    # ### end Alembic commands ###
